name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run flake8
        run: flake8 ./parking_app

      - name: Run isort
        run: isort --check-only --diff --profile black ./parking_app

      - name: Run black
        run: black --diff --check ./parking_app

      - name: Run mypy
        run: mypy ./parking_app

      - name: Run pytest
        run: pytest -v ./parking_app/tests
